"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Provider = exports.createInterstellarDimension = exports.createBaseDimension = exports.createStore = exports.setStore = exports.getStore = void 0;
const createBaseDimension_1 = require("./createBaseDimension");
Object.defineProperty(exports, "createBaseDimension", { enumerable: true, get: function () { return createBaseDimension_1.createBaseDimension; } });
const createInterstellarDimension_1 = require("./createInterstellarDimension");
Object.defineProperty(exports, "createInterstellarDimension", { enumerable: true, get: function () { return createInterstellarDimension_1.createInterstellarDimension; } });
const storeRegistry_1 = require("./storeRegistry");
Object.defineProperty(exports, "getStore", { enumerable: true, get: function () { return storeRegistry_1.getStore; } });
Object.defineProperty(exports, "setStore", { enumerable: true, get: function () { return storeRegistry_1.setStore; } });
Object.defineProperty(exports, "createStore", { enumerable: true, get: function () { return storeRegistry_1.createStore; } });
const Provider_1 = require("./Provider");
Object.defineProperty(exports, "Provider", { enumerable: true, get: function () { return Provider_1.Provider; } });
